# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PCIe.xdc

# Block Designs: bd/PCIe/PCIe.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe || ORIG_REF_NAME==PCIe} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_util_ds_buf_0_0/PCIe_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_util_ds_buf_0_0 || ORIG_REF_NAME==PCIe_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_xdma_0_1/PCIe_xdma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_xdma_0_1 || ORIG_REF_NAME==PCIe_xdma_0_1} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_clk_wiz_0_0/PCIe_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_clk_wiz_0_0 || ORIG_REF_NAME==PCIe_clk_wiz_0_0} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_mig_7series_0_0/PCIe_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_mig_7series_0_0 || ORIG_REF_NAME==PCIe_mig_7series_0_0} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_axi_mem_intercon_0/PCIe_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_axi_mem_intercon_0 || ORIG_REF_NAME==PCIe_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_rst_mig_7series_0_100M_1/PCIe_rst_mig_7series_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_rst_mig_7series_0_100M_1 || ORIG_REF_NAME==PCIe_rst_mig_7series_0_100M_1} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_auto_us_1/PCIe_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_auto_us_1 || ORIG_REF_NAME==PCIe_auto_us_1} -quiet] -quiet

# IP: bd/PCIe/ip/PCIe_auto_cc_1/PCIe_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PCIe_auto_cc_1 || ORIG_REF_NAME==PCIe_auto_cc_1} -quiet] -quiet

# XDC: bd/PCIe/PCIe_ooc.xdc
